language: node_js
node_js:
  - "8.2.1"
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
jobs:
  include:
    - stage: CI CD For WSO2 API Cloud 
      install:
      - npm install newman
      script:
      - echo "Start deploying the managed REST API to WSO2 Development Environment"
      - node_modules/.bin/newman run DeployAPI/WSO2_API_PUBLISHER.postman_collection.json -e DevEnvironment/Development.postman_environment.json --insecure --bail || travis_terminate 1;
      
      - echo "Start testing the REST API in WSO2 Development Environment"
      - newman run TestAPI/TestAPI.postman_collection.json -e DevEnvironment/Development.postman_environment.json --insecure --bail || travis_terminate 1;

      - echo "Start deploying the managed REST API to WSO2 Staging Environment"
      - node_modules/.bin/newman run DeployAPI/WSO2_API_PUBLISHER.postman_collection.json -e StagingEnvironment/Staging.postman_environment.json --insecure --bail || travis_terminate 1;

      - echo "Start testing the REST API in WSO2 Staging Environment"
      - node_modules/.bin/newman run TestAPI/TestAPI.postman_collection.json -e StagingEnvironment/Staging.postman_environment.json --insecure --bail || travis_terminate 1;

